# Generated by Django 5.0.4 on 2025-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Kurier'), ('pickup', 'Odbiór osobisty')], default=('pickup', 'Odbiór osobisty'), max_length=20),
        ),
    ]
