# Generated by Django 5.0.4 on 2025-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'W oczekiwaniu'), ('in_delivery', 'W dostawie'), ('completed', 'Dostarczone'), ('cancelled', 'Anulowane')], default=('pending', 'W oczekiwaniu'), max_length=50),
        ),
    ]
