# Generated by Django 5.0.4 on 2025-04-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_rename_adres_customer_addres_customer_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addres',
            new_name='address',
        ),
    ]
