# Generated by Django 5.0.4 on 2025-04-27 20:18

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cart_address'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='address.address'),
        ),
    ]
