# Generated by Django 5.0.4 on 2025-04-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
